### ISSUE TITLE
Fails to push Alert to ntfy when no message or file attachment is specified

### ISSUE THREAD

**Issue by Laflamme** [FoxxMD/deploy-ntfy-alerter#1]
```
Komodo Alert Payload: {
  ts: 1734363809179,
  resolved: true,
  level: "OK",
  target: { type: "Stack", id: "675f2b0370fff236be04d528" },
  data: {
    type: "StackAutoUpdated",
    data: {
      id: "675f2b0370fff236be04d528",
      name: "redacted",
      server_id: "675efb5470fff236be04d19f",
      server_name: "redacted",
      images: [ "redacted/redacted:latest" ]
    }
  },
  resolved_ts: 1734363809179
}
Error: Failed to push Alert to ntfy
    at file:///app/notifiers/ntfy/program.ts:145:17
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async ext:deno_http/00_serve.ts:369:18
Caused by Error: Error occurred while trying to push to ntfy
    at pushAlert (file:///app/notifiers/ntfy/program.ts:117:19)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async file:///app/notifiers/ntfy/program.ts:137:13
    at async ext:deno_http/00_serve.ts:369:18
Caused by Error: No message or file attachment specified
    at publish (file:///deno-dir/npm/registry.npmjs.org/ntfy/1.7.0/dist/NtfyClient.js:126:15)
    at pushAlert (file:///app/notifiers/ntfy/program.ts:105:19)
    at file:///app/notifiers/ntfy/program.ts:137:19
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async ext:deno_http/00_serve.ts:369:18
```

**Comment by FoxxMD** [comment]
Looks like ntfy doesn't like it when the `message` payload is an empty string

**Comment by FoxxMD** [comment]
This should be resolved in the newest [`latest` image tag](https://hub.docker.com/repository/docker/foxxmd/komodo-ntfy-alerter/tags/latest/sha256-a84f990d4868c362bd095b79f472be044d1ac63ae16d14e690bc6d00da37acb5)

Additionally, these ENV options have been added and can be used in the compose stack:

```
 # Prefixes messages with a checkmark when the Alert is in the 'Resolved' state
 #INDICATE_RESOLVED=true

 # Filter if an alert is pushed based on its Resolved status
 # * leave unset to push all alerts
 # * otherwise, alerts will only be pushed if Alert is one of the comma-separated states set here
 #ALLOW_RESOLVED_TYPE=resolved,unresolved
```

**Comment by Laflamme** [comment]
That was quick; thank you very much!
